# install: conda env create -f environment.yml
# update:  conda env update -f environment.yml

name: acq1
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - ffmpeg
  - matplotlib
  - tqdm
  - pip:
    - pysimplegui==4.60.5
    - opencv-python
    - scipy
    - psychopy
    - nidaqmx